ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "http01"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "traefik"
  tls:
    enabled: false

nexusProxy:
  enabled: true
  env:
    nexusDockerHost: container.lab.local
    nexusHttpHost: nexus.lab.local

# service:
#   enabled: true
#   name: sonatype-nexus
#   targetPort: 8081
#   port: 8081

persistence:
  storageClass: longhorn 
  storageSize: 8Gi

resources:
  requests:
    cpu: 250m
    # Based on https://support.sonatype.com/hc/en-us/articles/115006448847#mem
    # and https://twitter.com/analytically/status/894592422382063616:
    #   Xms == Xmx
    #   Xmx <= 4G
    #   MaxDirectMemory >= 2G
    #   Xmx + MaxDirectMemory <= RAM * 2/3 (hence the request for 4800Mi)
    #   MaxRAMFraction=1 is not being set as it would allow the heap
    #     to use all the available memory.
    memory: 4800Mi